### ISSUE TITLE
Is CsvToCollection.coffee still used?

### ISSUE THREAD

**Issue by dandv** [livingyang/csv-to-collection#1]

**Comment by livingyang** [comment]
Yes, I still use it in my project :)

**Comment by dandv** [comment]
How is it used... ? Looks like [the .js](https://github.com/livingyang/csv-to-collection/blob/master/CsvToCollection.js) does all that the .coffee does, and more.

**Comment by livingyang** [comment]
coffeescript is not necessary, only CsvToCollection.js package to your project. I just updated the readme.md.
