### ISSUE TITLE
modify to not stamp on existing collection

### ISSUE THREAD

**Issue by dcsan** [livingyang/csv-to-collection#2]
since i want to just load the data in an existing collection, i added this

``` coffee
  if (this[collectionName] instanceof Meteor.Collection)
    collection = this[collectionName]
  else
    collection = new Meteor.Collection(collectionName)
```

however since i converted all your code to coffeescript so i could read it more easily, i can't easily send a pull request.

**Comment by livingyang** [comment]
You can define a global object to save all collectiones.
