### ISSUE TITLE
[feature] enable loading of existing collections

### ISSUE THREAD

**Issue by dcsan** [livingyang/csv-to-collection#4]
you could use something like [collection-helpers](https://github.com/dburles/meteor-collection-helpers) to add a `.loadCsv` method to existing collections.
it could be a bit nicer sugar than passing a collection name to the loader.

**Comment by livingyang** [comment]
I dont like modify Object::prototype, but I will consider provide a function like AddCsvToCollection

**Comment by livingyang** [comment]
Now ctc.AddCsvToCollection is work.
